# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vTyQHjymj-9h1e4jnUfQhR8GWw4stn4p
"""

# Importing Libraries
import ast
import pandas as pd
import seaborn as sns
from datasets import load_dataset
import matplotlib.pyplot as plt

# Loading Data
dataset = load_dataset('lukebarousse/data_jobs')
df = dataset['train'].to_pandas()

# Data Cleanup
df['job_posted_date'] = pd.to_datetime(df['job_posted_date'])
df['job_skills'] = df['job_skills'].apply(lambda x: ast.literal_eval(x) if pd.notna(x) else x)

df_US = df[df['job_country']== 'United States']

df_skills = df_US.explode('job_skills')
df_skills[['job_title','job_skills']]

df_skills_count = df_skills.groupby(['job_skills', 'job_title_short']).size()
df_skills_count = df_skills_count.reset_index(name='skill_count')
df_skills_count.sort_values(by='skill_count', ascending=False, inplace=True)
df_skills_count

df_skills_count = df_skills.groupby(['job_skills', 'job_title_short']).size()
df_skills_count = df_skills_count.reset_index(name='skill_count')
df_skills_count.sort_values(by='skill_count', ascending=False, inplace=True)
df_skills_count

job_titles = df_skills_count['job_title_short'].unique().tolist()
job_titles = sorted(job_titles[:3])
job_titles

print(job_titles)
print(df_skills_count['job_title_short'].unique())

print(df_skills_count.columns.tolist())

# Create figure with 3 subplots (one for each job title)
fig, axes = plt.subplots(3, 1, figsize=(8, 8))

# Plot for each job
for i, job in enumerate(['Data Analyst', 'Data Engineer', 'Data Scientist']):
    # Get top 5 skills for this job
    top_skills = df_skills_count[df_skills_count['job_title_short'] == job].head(5)

    # Create horizontal bar plot
    axes[i].barh(top_skills['job_skills'], top_skills['skill_count'])
    axes[i].set_title(job)
    axes[i].invert_yaxis() # Highest skill at top

    # Remove y-axis label
    axes[i].set_ylabel('')



# Add main title
plt.suptitle('Top 5 Skills by Job Title', fontsize=16, y=1.02)
plt.tight_layout()
plt.show()

df_job_title_count = df_US['job_title_short'].value_counts().reset_index(name='jobs_total')

df_skills_perc = pd.merge(df_skills_count, df_job_title_count, how='left', on= 'job_title_short')

df_skills_perc['skill_percent']= 100* df_skills_perc['skill_count']/df_skills_perc['jobs_total']
df_skills_perc

# Create figure with 3 subplots (one for each job title)
fig, axes = plt.subplots(3, 1, figsize=(5, 5))

# Plot for each job
for i, job in enumerate(['Data Analyst', 'Data Engineer', 'Data Scientist']):
    # Get top 5 skills for this job
    top_skills = df_skills_perc[df_skills_perc['job_title_short'] == job].head(5)
    # Create horizontal bar plot using seaborn
    sns.barplot(data=top_skills, x='skill_percent', y='job_skills', hue='job_skills', ax=axes[i], palette='viridis', legend=False)
    axes[i].set_title(job)
    axes[i].invert_yaxis() # Highest skill at top

    # Remove y-axis label
    axes[i].set_ylabel('')
    axes[i].set_xlabel('Skill Percentage') # Add x-axis label for clarity

# Add main title
plt.suptitle('Top 5 Skills by Job Title', fontsize=16, y=1.02)
plt.tight_layout()
plt.show()

# Create figure with 3 subplots (one for each job title)
fig, axes = plt.subplots(3, 1, figsize=(8, 8))

# Plot for each job
for i, job in enumerate(['Data Analyst', 'Data Engineer', 'Data Scientist']):
    # Get top 5 skills for this job
    top_skills = df_skills_perc[df_skills_perc['job_title_short'] == job].head(5)
    # Create horizontal bar plot using seaborn
    sns.barplot(data=top_skills, x='skill_percent', y='job_skills', hue='job_skills', ax=axes[i], palette='viridis', legend=False)
    axes[i].set_title(job)
    axes[i].invert_yaxis() # Highest skill at top

    # Remove y-axis label
    axes[i].set_ylabel('')
    axes[i].set_xlabel('Skill Percentage') # Add x-axis label for clarity

    for n, v in enumerate(top_skills['skill_percent']):
      axes[i].text(v + 1, n, f'{v:.0f}%', va='center')

# Add main title
plt.suptitle('Top 5 Skills by Job Title', fontsize=16, y=1.02)
plt.tight_layout()
plt.show()



# Importing Libraries
import ast
import pandas as pd
import seaborn as sns
from datasets import load_dataset
import matplotlib.pyplot as plt

# Loading Data
dataset = load_dataset('lukebarousse/data_jobs')
df = dataset['train'].to_pandas()

# Data Cleanup
df['job_posted_date'] = pd.to_datetime(df['job_posted_date'])
df['job_skills'] = df['job_skills'].apply(lambda x: ast.literal_eval(x) if pd.notna(x) else x)

df_DA_US = df[(df['job_title'] == 'Data Analyst') & (df['job_country'] == 'United States')].copy()
df_DA_US['job_posted_month_no'] = df_DA_US['job_posted_date'].dt.month
df_DA_US_explode = df_DA_US.explode('job_skills')
df_DA_US_explode

pivot = df_DA_US_explode.pivot_table(index='job_posted_month_no', columns='job_skills', aggfunc='size', fill_value=0)
pivot.loc['Total'] = pivot.sum()
pivot = pivot[pivot.loc['Total'].sort_values(ascending=False).index]
pivot = pivot.drop('Total')
pivot

DA_totals = df_DA_US.groupby('job_posted_month_no').size()
df_DA_US_percent = pivot.div(DA_totals/100, axis=0)

df_plot = df_DA_US_percent.iloc[: , :5]
sns.lineplot(data=df_plot, dashes = False, palette ='tab10')
sns.set_theme(style='ticks')
sns.despine()

plt.title('Trending top skills for Data Analysts in the US')
plt.ylabel('Likelihood in job posting')
plt.xlabel('2023')
plt.legend().remove()

from matplotlib.ticker import PercentFormatter
ax = plt.gca()
ax.yaxis.set_major_formatter(PercentFormatter(decimals=0))

for i in range(5):
    plt.text(11.2, df_plot.iloc[-1, i], df_plot.columns[i])